### ISSUE TITLE
Extending to continuous treatment

### ISSUE THREAD

**Issue by cardifquang** [soda-inria/causal_model_selection#1]
Hello,

This is Quang from BNP Paribas Cardif. 

We’re working on this topic as well, and I’ve come to this repo, I’ve read the paper, and just wow, this is amazing. The paper was very clear, and with truly high quality findings. 
But it only covers the binary treatments.

Would you consider extending to continuous treatment? 

This would be very helpful.

**Comment by strayMat** [comment]
Hi, thank you for the compliment. It is a pleasure to see that the paper is read and appreciated ! 
 
The extension to the continous treatment would be very interesting indeed, but I am not considering it right now, since I am currently working on exploring other sources of bias than confounding on a real world case. 

Maybe in the future when I'll have more time !
